# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool: Default

steps:
  - task: PowerShell@2
    inputs:
      filePath: 'build.ps1'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'Output/install/'
      Contents: '*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/ArtifactsToBePublished'
